# Generated by Django 4.0.4 on 2022-05-05 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.IntegerField(default=1, verbose_name='operation number')),
                ('state', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En cours'), ('done', 'Fait')], default='draft', max_length=7, verbose_name='operation state')),
                ('contact', models.CharField(max_length=70, verbose_name='client or provider name')),
                ('m_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('rtn', 'Retour')], default='out', max_length=3, verbose_name='operation type')),
                ('date', models.DateField(max_length=255, verbose_name='date')),
                ('annexe', models.CharField(blank=True, max_length=255, null=True, verbose_name='document annexe of this operation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_operations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='quantity')),
                ('unit', models.CharField(max_length=30, verbose_name='unit')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='stock.product')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.operation')),
            ],
        ),
    ]
