# Generated by Django 4.0.4 on 2022-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_operation_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='quantity'),
        ),
    ]
