# Generated by Django 4.0.4 on 2022-05-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ('-created_at',), 'verbose_name': 'Opération', 'verbose_name_plural': 'Opérations'},
        ),
    ]
