# Generated by Django 4.0.4 on 2022-06-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_operation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name="cout d'achat"),
        ),
    ]
