# Generated by Django 4.0.4 on 2022-06-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_qty',
            field=models.FloatField(blank=True, null=True, verbose_name='ancienne quantité'),
        ),
    ]
