# Generated by Django 4.0.4 on 2022-06-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_newuser_avatar_newuser_contact_id_newuser_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelTable(
            name='newuser',
            table='auth_user',
        ),
    ]
