# Generated by Django 4.0.4 on 2022-05-05 15:55

import apps.stock.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inventories', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ratio', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ratio')),
                ('rouding', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, verbose_name='Ratio')),
                ('type', models.CharField(choices=[('bigger', 'Bigger'), ('reference', 'Reference'), ('smaller', 'Smaller')], default='consu', max_length=64, verbose_name='type')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.categoryuom')),
            ],
            options={
                'verbose_name': 'Uom',
                'verbose_name_plural': 'Uom',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('prod_type', models.CharField(choices=[('storable', 'Storable product'), ('service', 'Service'), ('consumable', 'Consumable')], default='storable', max_length=64, verbose_name='type')),
                ('category', models.CharField(blank=True, max_length=40, null=True, verbose_name='category')),
                ('code', models.CharField(blank=True, max_length=80, null=True, verbose_name='code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('photo_url', models.ImageField(blank=True, default='product/default_product.png', null=True, storage=apps.stock.models.RenameImage(), upload_to=apps.stock.models.image_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=apps.stock.models.RenameImage(), upload_to=apps.stock.models.image_path)),
                ('uom', models.CharField(max_length=30, verbose_name='Unit of measure')),
                ('providers', models.CharField(blank=True, max_length=120, null=True, verbose_name='providers')),
                ('real_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='real quantity')),
                ('virtual_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='virtual quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='sale price')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='purchase cost')),
                ('alert_stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='alert stock')),
                ('optimal_stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='good stock')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='initial quantity')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_product', to='stock.product')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_inventory', to='stock.inventory')),
            ],
        ),
    ]
