# Generated by Django 4.0.4 on 2022-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='providers'),
        ),
    ]
