# Generated by Django 4.0.4 on 2022-05-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_product_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alert_stock',
            field=models.IntegerField(default=0, verbose_name='alert stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='optimal_stock',
            field=models.IntegerField(default=0, verbose_name='good stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='real_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='real quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=8, verbose_name='purchase cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=8, verbose_name='sale price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='virtual_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='virtual quantity'),
        ),
    ]
