# Generated by Django 4.0.4 on 2022-05-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_product_alert_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='providers'),
        ),
    ]
