# Generated by Django 4.0.4 on 2022-05-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_product_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='isApply',
            field=models.BooleanField(default=False, verbose_name='est appliqué'),
        ),
        migrations.AddField(
            model_name='product',
            name='isArchived',
            field=models.BooleanField(default=False, verbose_name='est archivé'),
        ),
    ]
