# Generated by Django 4.0.4 on 2022-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_inventory_isapply_product_isarchived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='initial_quantity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='initial quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='real_quantity',
            field=models.FloatField(default=0, verbose_name='real quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.FloatField(default=1, verbose_name='purchase cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=1, verbose_name='sale price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='virtual_quantity',
            field=models.FloatField(default=0, verbose_name='virtual quantity'),
        ),
    ]
