# Generated by Django 4.0.4 on 2022-06-01 09:10

import apps.stock.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0007_alter_inventoryitem_initial_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='catégorie')),
            ],
            options={
                'verbose_name': "Groupe d'unité",
                'verbose_name_plural': "Groupe d'unités",
            },
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventaire', 'verbose_name_plural': 'Inventaires'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='uom',
            options={'verbose_name': 'Unité de mesure', 'verbose_name_plural': 'Unité de mesures'},
        ),
        migrations.RemoveField(
            model_name='uom',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.uom', verbose_name='futur unité de mesure'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créer le'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inventories', to=settings.AUTH_USER_MODEL, verbose_name='créer par'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_inventories', to=settings.AUTH_USER_MODEL, verbose_name='modifié par'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=80, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_product', to='stock.product', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_inventory', to='stock.inventory', verbose_name='inventaire'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alert_stock',
            field=models.IntegerField(default=0, verbose_name='qté alerte'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="catégorie d'article"),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créer le'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='créer par'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_products', to=settings.AUTH_USER_MODEL, verbose_name='modifié par'),
        ),
        migrations.AlterField(
            model_name='product',
            name='optimal_stock',
            field=models.IntegerField(default=0, verbose_name='qté idéale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_url',
            field=models.ImageField(blank=True, default='product/default_product.png', null=True, storage=apps.stock.models.RenameImage(), upload_to=apps.stock.models.image_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='fournisseurs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='real_quantity',
            field=models.FloatField(default=0, verbose_name='stock réel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.FloatField(default=1, verbose_name="cout d'achat"),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=1, verbose_name='prix de vente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.CharField(max_length=30, verbose_name='unité de mesure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='virtual_quantity',
            field=models.FloatField(default=0, verbose_name='stock virtuel'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='name',
            field=models.CharField(max_length=255, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='ratio'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='rouding',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, verbose_name='arrondi au'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='type',
            field=models.CharField(choices=[('bigger', 'Bigger'), ('reference', 'Reference'), ('smaller', 'Smaller')], default='reference', max_length=64, verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='CategoryUOM',
        ),
        migrations.AddField(
            model_name='uom',
            name='uom_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.parentuom'),
        ),
    ]
