# Generated by Django 4.0.4 on 2022-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='semi_wholesale_price',
            field=models.FloatField(default=1, verbose_name='prix de demi-gros'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.FloatField(default=1, verbose_name='prix de gros'),
        ),
    ]
