# Generated by Django 4.0.4 on 2022-05-26 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_contact', to='contacts.company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_client',
            field=models.BooleanField(default=True, verbose_name='est client'),
        ),
    ]
