# Generated by Django 4.0.4 on 2022-05-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_company_options_remove_company_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('mr', 'Monsieur'), ('mme', 'Madame')], default='mr', max_length=3, verbose_name='genre'),
        ),
    ]
