# Generated by Django 4.0.4 on 2022-05-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_client',
        ),
        migrations.AddField(
            model_name='contact',
            name='c_type',
            field=models.CharField(choices=[('company', 'Entreprise'), ('deliver', 'Livreur'), ('client', 'Client')], default='client', max_length=7, verbose_name='type de contact'),
        ),
    ]
