# Generated by Django 4.0.4 on 2022-05-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_is_client_contact_c_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='est archivé'),
        ),
    ]
