# Generated by Django 4.0.4 on 2022-06-20 16:44

import apps.base.rename_image
import apps.contacts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='c_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.BooleanField(default=True, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=40, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='for_invoice',
            field=models.BooleanField(default=True, verbose_name='For Invoice'),
        ),
        migrations.AddField(
            model_name='contact',
            name='img',
            field=models.ImageField(blank=True, default='contact/default_partner.png', max_length=255, null=True, storage=apps.base.rename_image.RenameImage(), upload_to=apps.contacts.models.image_path),
        ),
        migrations.AddField(
            model_name='contact',
            name='not_email',
            field=models.BooleanField(default=False, verbose_name='No Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact', verbose_name='Parent du contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='provider',
            field=models.BooleanField(default=True, verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='contact',
            name='street_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street Other'),
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual'), ('address', 'Address'), ('contact', 'Contact')], default='company', max_length=64, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
