# Generated by Django 4.0.4 on 2022-06-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_options_remove_contact_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='not_email',
            new_name='has_not_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='customer',
            new_name='is_customer',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='for_invoice',
            new_name='is_for_invoice',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='provider',
            new_name='is_provider',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
